### PR TITLE
Add option to hide tray icon

### LINKED ISSUE #74: Make tray(menubar) icon optional
On OS X tray icon after click allows to switch window state which is duplication of standard os controls also it duplicate notification info from dock icon, in result it's not so useful for OS X users.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/29952616-make-tray-menubar-icon-optional?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #189: Disable tray icon in OSX
## My Setup

- **My OS name and version**:  MacOS 10.11.4
- **My current app version**: Version 1.3.1 (15)

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily
## Description

A tray icon is always shown in MacOS X and there is no way to disable it.
#### Current Behavior

There is no way to disable the tray icon in MacOS X

screen shot 2016-05-12 at 11 28 59 am
#### Expected Behavior

There should be a preference window allowing us to disable this feature. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34168493-disable-tray-icon-in-osx?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #74 
Closes #189 

Add option to hide tray icon

image

### CODE REVIEW

**Comment by sampaiodiego** [comment]
if the tray icon is hidden and I close the app, will it keep running or will it be completely closed?

**Comment by alexbrazier** [comment]
@sampaiodiego I haven't changed the behaviour of the app, so I you choose to hide it, and close the application it will still be running and you will still receive notifications. To reopen on windows you will have to click the launch icon again.

On mac I think the expected behaviour is for it to stay open until to tell it to close by selecting Quit from the menu.

What do you think it should do?

I could disable the toggle button on Windows?

**Comment by sampaiodiego** [comment]
for me the expected behavior would be if no tray icon is present, when I close the app it sould stop running.

but maybe we should make it clear. like some apps do, when you close it (clicking the X icon), it shows a message saying it is still running and you can re-open from the tray icon.

**Comment by alexbrazier** [comment]
@sampaiodiego What OS are you on?

On mac the default behaviour for most apps is to stay open after closing. E.g. closing mail/whatsapp doesn't stop the app from running, but they don't have tray icons.

On Windows maybe we should disable the option, as the tray icon is hidden away, and shouldn't really be a problem. I agree that if there is no tray icon on Windows I would expect the app to be closed.

I'm not sure what is expected on Linux.

The issues only mention the tray icon being an issue on macOS, so should I just change this to only show the toggle option on mac?

**Comment by geekgonecrazy** [comment]
Maybe the setting could be called "close on exit"?  I've never seen an app that's put to the background that doesn't have an icon somewhere.  This would actually be a very frustrating behaviour to me.

Osx I would understand wanting to remove the icon from dock if it's there.  But the on in the menu bar I think should be required if the app is in the background.

**Comment by sampaiodiego** [comment]
> The issues only mention the tray icon being an issue on macOS, so should I just change this to only show the toggle option on mac?

@alexbrazier yes, I think it's better than allowing it to be hidden on every OS for now.. as @geekgonecrazy I would be frustrated as well if I close the app on Windows and there is no tray icon to re-open it.

after that we can improve the UX adding messages like @geekgonecrazy and me mentioned 😉 

oh, and welcome to the team @alexbrazier .. you're doing a very good job :D

**Comment by alexbrazier** [comment]
Thanks! I've changed it so that it is only enabled for mac.
I also changed it to merge into another branch in PR, as there were conflicting changes

**Pull request merged**
