### PR TITLE
feat: Flash root window on all platforms

### PR DESCRIPTION
**Pull request by Mephistophiles**
Reduce win32 restriction for flashFrame

Maybe I should have an option in the config for this, what do you say?

### CODE REVIEW

**Comment by tmartincpp** [comment]
Hello,

I have made the same kind of modification (allow Linux in addition to Windows) :
https://github.com/tmartincpp/Rocket.Chat.Electron/commit/a59e7ddfd3be47ea46050a8e9464f4598041135b#diff-99883d1c521e67a9432579aaf9026a31ef591df0da751b4700afd8f6bb39e9e5

I have tested it successfully (all mentions will triggers the taskbar flash).

I think that it would be a great feature to support flashing for more platforms.

Should I do another pull request ?

**Comment by bartelme** [comment]
I really agree this would be nice.  I feel like it used to work for us in 2.X but i may be confused.  I have team members using skype on their windows systems to let others know they have rocket chat messages waiting on the linux system.

**Comment by Mephistophiles** [comment]
Oh, I based on the develop branch, my failure. Rebased on the master branch.

**Review by tassoevan — APPROVED** [review]

**Comment by pierre-lehnen-rc** [comment]
On linux, this change is causing the app to steal focus from other apps whenever the user is mentioned or receives a DM (even across different desktops)

**Comment by geekgonecrazy** [comment]
Yeah this is very annoying on linux.  :see_no_evil: Especially in i3 where focus means the mouse is also moved

**Comment by Mephistophiles** [comment]
How about making the option "flash window on notifications" next to the "Show tray icon" (disabled for Linux by default)?

**Comment by geekgonecrazy** [comment]
I think i'd personally even be ok having to turn it off via a flag or environment variable.  Cause I know adding an option is a good more work :)

**Pull request merged**
