### PR TITLE
Add missing Services menu in application menu on macOS

### LINKED ISSUE #496: Missing Services menu in application menu on macOS
## My Setup
- Operating System: macOS Sierra 10.12.6
- App Version: 2.8.0

- [ x ] I have tested with the latest version
- [ x ] I can simulate the issue easily

## Description
I use "Services" for some predefined actions.

Missing Services menu in Rocket.Chat+ application menu:
rocketchat

How it looks correctly for example in Finder:
finder

### Current Behavior
I can't run my predefined action while the Rocket.Chat+ application is in the foreground.

### Expected Behavior
It should be there, so I can use the Services like in any other application.

### PR DESCRIPTION
**Pull request by phidlipus**
@RocketChat/core 

Closes #496

### CODE REVIEW

**Comment by gdelavald** [comment]
Thanks for doing this PR. We'll evaluate and get back to you if there are any changes needed.

**Comment by phidlipus** [comment]
Tested on macOS Sierra 10.12.6:
rocketchat_services

**Comment by gdelavald** [comment]
@phidlipus is the Services menu expected to be populated automatically?

**Comment by phidlipus** [comment]
@gdelavald Services menu will be populated only if you have configured some services. By default, if you haven't configured some services you will see only "Services Preferences".
The service menu should open, when you place your cursor on it.

**Comment by tomasgatial** [comment]
@gdelavald To my understanding, services menu is stateful, it should populate e.g. if you select a text within the application window. Then you can choose e.g. from text selection related services. 

The electron documentation does say it is a system standard menu. Why keep it disabled?

**Comment by gdelavald** [comment]
@phidlipus It's looking good! If I may add a suggestion, could you also add the services submenu to the context menu? I think that would improve the PR even further.
Right now the context menu is being modified in the SpellCheck.js file:
https://github.com/RocketChat/Rocket.Chat.Electron/blob/26d9cca6fb747a56228086ab48c44c91cbe0362f/src/public/lib/SpellCheck.js#L183-L217
I think it would be trivial to add the same submenu there.

**Comment by alexbrazier** [comment]
@gdelavald I might be wrong, but I don't think its common to have the services menu in the context menu

**Comment by gdelavald** [comment]
@alexbrazier I thought I saw some examples of it being useful. Haven't used osx long enough to be sure, I'll leave as is then, if someone feels like it could be useful we can discuss this in the future.

**Comment by phidlipus** [comment]
Thanks for merge.

**Pull request merged**
