### PR TITLE
Windows notification issues

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

- Fix issue with notification resize
- Fix notification height with multiple monitors
- Make it so you can't highlight the text in a notification

These still appear to be problems:
- [x] Fix issue with some notifications being blank (image showing, but text missing) - Could this be an issue with Rocket.Chat itself not sending the notification?
- [x] Fix issue with notification taking focus while typing a message to someone else on the desktop app

### CODE REVIEW

**Comment by rodrigok** [comment]
@alexbrazier Can you update with develop branch to fix build errors on travis?

**Comment by alexbrazier** [comment]
@rodrigok I've merged with develop, but still getting an error with travis

```
Error: Cannot find valid "Developer ID Installer" to sign standalone installer, please see https://github.com/electron-userland/electron-builder/wiki/Code-Signing

**Comment by alexbrazier** [comment]
There also appears to be another issue that the notifications are taking focus over Rocket.Chat, so if you are typing it takes focus away when you get a notification. I was hoping setting `focusable:false` would fix that, but it still doesn't work. Any ideas what could fix it?

**Comment by rodrigok** [comment]
I guess I found the problem https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by alexbrazier** [comment]
It seems there isn't really a way around it to get it to build, unless you can do it without the key?
Travis suggests doing something like this
https://docs.travis-ci.com/user/pull-requests#Pull-Requests-and-Security-Restrictions
```
script:
   - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
   - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
```

So you might have to change the travis build script to have this at the end
```
if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then
    npm run release -- --ia32 --x64
else
    npm run prerelease
fi
```

**Comment by alexbrazier** [comment]
This PR is now ready to merge

**Pull request merged**
