### PR TITLE
fix: Video calls open again on Electron window

### LINKED ISSUE #2480: `Open Video Chat using Application Window` option broken for server 5.0
**Describe the bug**
If one use recent app version 3.8.8 with latest server version like 5.0.4, option `Open Video Chat using Application Window` do not work. Jitsi call is opened in default browser window.

What operating system and which version? Windows 10
Which version of Rocket.Chat (Server)? 5.0.3
Which version of Rocket.Chat.Electron (Electron/Desktop)? 3.8.8
Is there any setting relevant changed? Update from 4.x to 5.x of server version

**To Reproduce**
1. Setup Jitsi app with new Video Conf system in 5.X server version
2. Turn on option `Open Video Chat using Application Window` in Settings of Desktop app 
3. Test Jitsi call
4. See that call opens in default browser

**Expected behavior**
Jitsi call opens in desktop app sub window even on server version 5.X

**Screenshots**
No

**Additional context**
On pre 5.0 versions of server with same 3.8.8 version of Desktop app Jitsi call starts in Desktop app sub window.

### PR DESCRIPTION
**Pull request by jeanfbrito**
Closes #2480

### CODE REVIEW

**Comment by chrisi51** [comment]
The opposite is happening ... VC oppens  in safari now while it was opening in electron window until the update ... 

we tried both positions of the "open video chat using application window" switch

**Comment by jeanfbrito** [comment]
@chrisi51 
This was a fix for the Video Conference from version 5.2 above. 
But I'm taking a look in what breaked the versions below 5.0

**Comment by chrisi51** [comment]
thx for checking ... were on an older version due to UCS: 
Version 3.18.2

**Comment by jeanfbrito** [comment]
@chrisi51 your server is public? Could I connect to it to test? You can reach me on open.rocket.chat if positive.

**Comment by chrisi51** [comment]
no its private :( and also not very easy to bring it public for testing right now :)

**Comment by jeanfbrito** [comment]
no problem, I'm spinning up some servers to test it

**Comment by jeanfbrito** [comment]
@chrisi51 already fixed it, will make a release today yet. The problem was the way jitsi domain string comes on some servers.

**Comment by chrisi51** [comment]
@jeanfbrito yep its working - thx!

**Comment by amsnek** [comment]
@jeanfbrito hmm not working for me either, using 3.8.11 + Jitsi + Rocketchat 5.1.3 -> still opening in (default) browser 
also cleared all %appdata% etc -> but no effect

**Comment by jeanfbrito** [comment]
This will work only on versions below 4.8.2 and above 5.2.
The Rocket.Chat 5.2 will be released soon and then it will start working on
it. We needed to change things because of the video conference on version 5
and it will be ready on this week release.


Em ter., 27 de set. de 2022 08:44, amsnek ***@***.***>
escreveu:

**Comment by amsnek** [comment]
> This will work only on versions below 4.8.2 and above 5.2.

Ah this makes sense, i wasnt sure if the 5.2 wasnt a typo since there is no 5.2 yet. Thanks, that is good to know.

**Comment by jeanfbrito** [comment]
Yeah I released the desktop before the server version to be ready when the
server updates.
I needed to change code inside the server this time, this is why this time
we need a server release. After that it will be working with any video
conference provider. Before was just jitsi and BBB.

Em ter., 27 de set. de 2022 09:16, amsnek ***@***.***>
escreveu:

**Pull request merged**
