### PR TITLE
feat: apple silicon universal support

### LINKED ISSUE #1875: Apple Silicon Support
## My Setup

- Operating System: 11.0.1
- App Version: 3.0.7
- Installation type: PKG

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
Due to the electron dependency Rocket.Chat will not open on Apple Silicon (M1) Macs.

### Current Behavior
Success app launch but nothing happens

### Expected Behavior
Ability to use application.

Electron 11 should be used to build Rocket.Chat

### PR DESCRIPTION
**Pull request by septs**
Closes #1875

## References

https://www.electronjs.org/blog/apple-silicon/
https://github.com/electron-userland/electron-builder/issues/5475
https://github.com/electron-userland/electron-builder/pull/5481

### CODE REVIEW

**Comment by septs** [comment]
@ggazzo request merge.

**Comment by septs** [comment]
image

**Comment by septs** [comment]
?

**Comment by septs** [comment]
@ggazzo

**Review by cazetto — APPROVED** [review]

**Pull request merged**
