### PR TITLE
[WIP] Electron update

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

- Update Electron from 0.36.10 to 1.4.3
- SPELLCHEKING IS NOT WORKING

### CODE REVIEW

**Comment by jGleitz** [comment]
> SPELLCHEKING IS NOT WORKING

If I comment in the spell checking code on this PR, it fails because `require('spellcheker')` fails. However, this also happens on `develop` so it’s a separate issue and not related to the updated Electron version, is it?

**Comment by jGleitz** [comment]
> SPELLCHEKING IS NOT WORKING

Under which circumstances is spellchecking not working? If I comment in the spellcheck code in this PR, it works for me (Ubuntu 16.04)

**Comment by geekgonecrazy** [comment]
@jGleitz great!  How else does this perform for you on Ubuntu 16.04?

I think only on osx probably broken.

**Comment by jGleitz** [comment]
> @jGleitz great! How else does this perform for you on Ubuntu 16.04?

Very well. I had the feeling text input was slightly faster, but I may be wrong as it’s already pretty good right now.

Most importantly, this PR fixes #206 (notifications are now done through system notifications instead of persistent alerts) which is *such a huge improvement*.

**Comment by geekgonecrazy** [comment]
@jGleitz great! thanks for the feedback!

**Pull request merged**
