### PR TITLE
[FIX] Resolves issue with timing out when Rocket.Chat is in the background …

### LINKED ISSUE #1260: Auto-Away on Windows 10 does not follow user's machine activity
## My Setup
- Operating System: Windows 10 (1709, 1803, and 1809)
- App Version: 2.15.3
- Installation type: exe built from source

- [X] I have tested with the latest version
- [X] I can simulate the issue easily

## Description
The Auto-Away functionality seems to only work when the Rocket.Chat.Electron app is in focus (vs minimized or just task tray)

### Current Behavior
Auto-Away goes to Away after the set 300 seconds when the user is still using their computer (keyboard/mouse activity)

### Expected Behavior
Auto-Away should track based on keyboard/mouse activity of the logged in user, irrespective of the minimized/maximized/taskbar state of the Rocket.Chat.Electron application

I did look at the source for 2.15.3, and the source library used for this detection on windows, and it is using the method recommended from microsoft.. Wondering if that thread is somehow getting suspended when Chromium/electron isn't in the foreground?

### PR DESCRIPTION
**Pull request by ChristineBoersen**
@RocketChat/electron

Closes #1260 

Resolves issue with Rocket.Chat client going to away when in the background. Solved it by explicitly setting the awayOnWindowBlur: false instead of relying on the default value

Also, shortened the idleTimeDetectionInterval to 5000 ms. The original value was 1/2 of the idleTimeLimit, which is way too long to change state (e.g. the default of 300 would only check every 150 seconds!)

### CODE REVIEW

**Comment by ChristineBoersen** [comment]
Just to add, this was only tested on a Windows 10 environment,

**Comment by tassoevan** [comment]
@ChristineBoersen Do you think it's okay for users to have two away detection policies? I mean, one for browser client (default of 300s) and another one for the desktop client (5s)?

**Comment by ChristineBoersen** [comment]
I think they should both be bumped up to 5s.

I'll most likely propose that same change when I do the PR on the non-electron version (working on adding some functionality for showing the time in non-online status similar to lync). They are all in nearly the same portions of code.

And a good chance, (as a second PR to both projects) I'll add it as a server setting, with a default of 5s, and make both clients read from the server provided setting.

________________________________

**Comment by tassoevan** [comment]
@ChristineBoersen While I agree that both would be shorter, the 300s threshold exist because away detection is more complicated on the browser environment -- that's why `awayOnWindowBlur` is a thing. With that being said, I'm convinced that it's hurting users to share the same preference and this PR is welcome in the next release.

**Comment by ChristineBoersen** [comment]
I agree (and after looking at how the browser side handles it agree it should be left alone for now) that the browser side is much more complicated since it can't call any OS hooks to truly know away/online

**Comment by vinceogne** [comment]
is this fixed in the 2.16.0 downloads for mac and pc?

**Comment by ChristineBoersen** [comment]
This fix would have only helped Windows. I know it was in the 2.15.5 version.

**Comment by vinceogne** [comment]
I tried Windows and Mac with version 2.16.0 and they both have the same issue.  2.15.5 seems to work fine for both.

**Comment by ChristineBoersen** [comment]
Unfortunately, all I did was donate the patch which was part of 2.15.5. My hands are out of the Rocket.Chat project at this point for other reasons... 

@tassoevan Any idea on the regression issue?

**Comment by tassoevan** [comment]
Version 2.16.0 landed with the bug described on #1364 and fixed by #1365, but a new patch release is blocked by problematic a behavior on auto-update for Windows users. I believe the most appealing alternative right now is not publish it for Windows users while update is failing.

**Comment by vinceogne** [comment]
any update on how to fix electron from changing to 'away' when in the background?  i've been stuck on 2.15.5 since it seems to be the last version where it worked correctly.  I just installed 2.17.8 and my status changes to away while still actively using other programs (osx 10.14.6)

**Comment by Nihixi** [comment]
version 2.17.7 also does not handle the status correctly

**Pull request merged**
