### PR TITLE
 [NEW] Show account status in menu bar

### PR DESCRIPTION
**Pull request by HappyTobi**
Add new feature to show account status in menu bar 
(implemented for all OS - actually there now special icons for windows and linux)

[Feature Request](https://github.com/RocketChat/Rocket.Chat.Electron/issues/703)
[Server Changes to activate function](https://github.com/RocketChat/Rocket.Chat/pull/11303)

Short video about the new feature
video

### CODE REVIEW

**Comment by gdelavald** [comment]
Looks awesome! Thanks for your contribution. I will wait for the server side PR to be merged before releasing this, but it should be soon.

**Comment by HappyTobi** [comment]
Thx

**Comment by jwallet** [comment]
seems like notification does not work anymore on windows after this pr

**Comment by HappyTobi** [comment]
I will Check that in the Eventim today and fix the issue.

**Comment by jwallet** [comment]
im thinking about adding next to the status dot that you added , i will like to add a way to show that there is new activity without breaking the appearance of rocket.chat logo, something like how Slack does it for the tray icon, a blue sky dot and when you hover the "Rocket.Chat+" title will change for "24 unread messages"

**Comment by HappyTobi** [comment]
so i fixed the problem with the default tray_icon. [Fix](https://github.com/RocketChat/Rocket.Chat.Electron/pull/766)

There some differences between the platforms while showing the tray icons and status.

OS X:
- use the template icon's and an title tag to give you some information (the title will be uses to visualize the user state)
- there no special icons to show badge state because of the dock implementation.
- There is only one icon to show badge state (rocket with exclamation mark)

Windows / Linux:
-  uses special icons for each badge state (1-9+)
- to show the user state we have to create some special icons (open)

**Comment by ccfiel** [comment]
In version 14.1 this does not work in linux ( ubuntu 16.04)

**Comment by ttepatti** [comment]
This also does not work for me on Linux (Debian 9.5 w/ Gnome 3.22.2)

**Pull request merged**
