### PR TITLE
[NEW] Disable autoupdate on windows installer

### LINKED ISSUE #849: Disable automatic updates with command line flag during install
## My Setup
- Operating System: Windows 10 x64
- App Version: 2.13.0

- [x ] I have tested with the latest version
- [x ] I can simulate the issue easily

## Description
We deploy the RocketChat application via an automatic software deployment and would love to disable automatic updates of the application, so we can control and deploy them centralized via software deployment.

### Current Behavior
RocketChat checks for updates and asks to update, if an update is available.

### Expected Behavior
Installation can be extended by "installer.exe /S /allusers /autoupdate=0" and the application is not checking for updates automatically.

### PR DESCRIPTION
**Pull request by HappyTobi**
[NEW] Allow setup to disable autoupdate

Closes #849 

you can run the installer with the option "/disableAutoUpdates" to disable the update function in rocket.chat (like the windows App Store version)

### CODE REVIEW

**Comment by Anguel** [comment]
/disableAutoUpdates does not seem to work for me on Windows 10, "Check updates on Start is still checked". Did uninstall and reinstall, same problem.

**Comment by nexidus** [comment]
I have installed it on a W10 1809 VM over the existing 2.13.3 and it worked. No checkbox for updated.

image

**Comment by josephbadow** [comment]
I'm facing the same problem, rocket.chat is still offering to check for updates. I tried several ways but all ended up the same:

**Updated an existing 2.13.3**
- Quit rocket.chat Client
- `rocketchat-setup-2.14.0.exe /S /allusers /disableAutoUpdates`
- Open rocket.chat Client
- AutoUpdate still enabled

**Fresh installation**
- Uninstalled 2.14.0 
- Removed `%appdata%\Rocket.Chat` 
- `rocketchat-setup-2.14.0.exe /S /allusers /disableAutoUpdates`
- Open rocket.chat Client
- AutoUpdate still enabled

It seems that the `update.json` file at `%appdata%\Rocket.Chat` is not created.

I created it manually with
```
{
	"canUpdate":false,
	"autoUpdate":false
}
```
and this removed the Update options in the about dialog.

**Comment by HappyTobi** [comment]
I will check that, i think we need an other installer option to copy the settings to all users.

**Comment by nexidus** [comment]
My command is without /allusers. Only /s /disableAutoUpdates
Maybe the /allusers command are the problem?

**Comment by HappyTobi** [comment]
I think so

**Comment by havx** [comment]
Copying the settings to "all users" during install does not work in an enterprise deployment since it would only apply to existing users on the machine. The application should honor `update.json` in the installation directory like `servers.json`, overriding what may be found in `%appdata%\Rocket.Chat`.

**Pull request merged**
