### PR TITLE
fix: Add reload after adding listeners to fix Houston page

### PR DESCRIPTION
**Pull request by jeanfbrito**
Closes #ISSUE_NUMBER

### CODE REVIEW

**Comment by trongtran810** [comment]
Hi @jeanfbrito,
Is this commit a fix for sometimes-issue( issue that happens sometimes, not usually):
- Error: Open the app=> Add an server URL=> Loading...( long, need to click to "reload server" button to show the web page normally)
- Normal: Open the app=> Add an server URL => Show the page immediately( maximum 3s)

**Comment by jeanfbrito** [comment]
Sorry @trongtran810 I didnt understood if you are saying that this didn't fixed your problem or is asking about it.
Could you please open an issue showing this problem with a video?

**Comment by trongtran810** [comment]
@jeanfbrito I was wondering if the problem that this commit fixed is the same the problem that I met. It's a sometimes-issue( it doesn't happen usually), so sorry I don't have the video now.
Could you detail the problem that  this commit fixed? Thank you

**Comment by jeanfbrito** [comment]
@trongtran810 the issue was that sometimes when the internet is disconnected or the server is offline when opening the app the screen become grey and show nothing. Now it will show the reload screen.

**Pull request merged**
