### PR TITLE
Switch webview [Work in Progress]

### PR DESCRIPTION
**Pull request by rodrigok**

### CODE REVIEW

**Comment by rodrigok** [comment]
@graywolf336 can you review this?

**Comment by graywolf336** [comment]
@rodrigok Sorry for so long, yes I will review it this week and get back with you

**Comment by graywolf336** [comment]
image
This is what I get when I first start up the project. I deleted my `~\AppData\Roaming\Rocket.Chat Dev` folder before starting.

**Comment by rodrigok** [comment]
@geekgonecrazy can u help us here? :smile:

**Comment by geekgonecrazy** [comment]
@rodrigok i'll take a look! :grinning:

**Comment by geekgonecrazy** [comment]
@rodrigok alright so I ran this code with out running npm install.  So it didn't have rollup.  Everything worked fine (other then the errors complaining about rollup).  I did npm install rollup, and then the UI is broke.

**Comment by graywolf336** [comment]
What's the progress on this @rodrigok @geekgonecrazy?

**Comment by geekgonecrazy** [comment]
Just have to get free time to work through this.  The upgrade of electron screwed with my code.

**Pull request closed without merging**
