### PR TITLE
[NEW] Rocket.Chat Download Manager for Client

### LINKED ISSUE #1155: Add Download progress bar
Where it can be seen the download progress bar?
if i am downloading multi-files how i can check if the download tasks all finished
and how i can resume or cancel download tasks ?

You need to add  Downloads Manager with thus options :+1: 
1-Download progress bar  (client)
2-Resume / Pause /Cancel option (client/Server)
3-History downloaded Files (client/Server)

### PR DESCRIPTION
**Pull request by HappyTobi**
NEW Feature for Rocket.Chat Client.
Add "Download Manager" to client to have a better overview about:
- the downloaded items
- download state (in sidebar)
- File Size

@RocketChat/electron
Check the look and feel please.
Maybe you will change some icon's I think

Closes #1155

Active Download:
Screen Shot 2019-04-15 at 15 46 55

Inactive Download:
Screen Shot 2019-04-15 at 15 47 41

### CODE REVIEW

**Comment by tassoevan** [comment]
While I'm doing a huge refactor for next version, I've come to the idea of using a panel at the same level as the landing/add a server, the webviews, and a new preferences panel. I'm also considering show update download progress in this "downloads panel". What do you think, @HappyTobi?

**Comment by HappyTobi** [comment]
@tassoevan yes why not, i think it‘s great to see the update progress.
Is there some graphic to get a better understandig about what‘s coming and how it looks ?

**Comment by tassoevan** [comment]
I'm sad to say this, but after around 2 years of intense changes in our codebase, this PR is not mergeable anymore. I'm glad to have some conversations with you, @HappyTobi, and your contributions were invaluable.

**Comment by HappyTobi** [comment]
@tassoevan no problem.

**Pull request closed without merging**
