### PR TITLE
fix: System locale not working in some languages

### LINKED ISSUE #2048: Translation is not used
## My Setup

- Operating System: Win10
- App Version: 3.2.2
- Installation type: rocketchat-setup-3.2.2.exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
The Interface translation is not working. 
I have german at the OS and german at Rocket.Chat - the Electron Interface stays english all the time.
The Shortcuts are translated for some reason.
image

### Current Behavior
The Electron App Interface is in english.

### Expected Behavior
The Electron App Interface should be the same as the OS.

### PR DESCRIPTION
**Pull request by jeanfbrito**
Closes #2048

Before:
image

After:
image

### CODE REVIEW

**Comment by CvH** [comment]
@jeanfbrito any chance to rebase your changes and merge ?

**Comment by binse03** [comment]
Hello, i am a german. The Translation is not that right. "Der Rücken" means in German this: https://www.linguee.de/deutsch-englisch/uebersetzung/r%C3%BCcken.html

 The right Translations is "Zurück".

And for "Nach vorne" sounds OK but not that nice. "Vorwärts" or "Vor" is much better.

**Comment by jeanfbrito** [comment]
Hello, as the community makes the translations we must find a native German speaker to review it.
And we would be happy if someone contribute to this translation.

**Comment by jeanfbrito** [comment]
https://developer.rocket.chat/v1/docs/translation-contribution-guidelines

**Pull request merged**
