### PR TITLE
Add tray and minimize-to-tray functionality

### PR DESCRIPTION
**Pull request by subesokun**
- If the window gets closed minimize window into the tray
- Tray shows alert icon in case there are unread messages or alerts + flash taskbar frame

### CODE REVIEW

**Comment by rodrigok** [comment]
Hi @subesokun, I've found some errors with this PR running in OS X

First, this changes adds a new menu in system menu bar, I don't know if is this necessary for OS X and the icon is very very big:

captura de tela 2015-07-11 as 17 02 38

Your changes changed the window close behavior, instead of hide the window in OS X, the window is been minimized.

Can you fix this problems?

**Comment by rodrigok** [comment]
There is another problem, now when I try to quit the application via Quit menu or Command + Q, the application is minimized and not closed.

I can't close the application anymore :)

**Comment by subesokun** [comment]
@rodrigok Thanks a lot for the feedback :) As I don't have OS X I could test it only with Windows and Linux (Ubuntu) but interesting that it behaves that different with OS X. I'll have a look on it and try to figure out how to avoid this issue.

**Comment by rodrigok** [comment]
@subesokun you can change this PR to another branch, so I can accept and we can work together, I don't have Linux and Windows here to test your changes, I can only test if you break something with the OS X version :D

**Comment by subesokun** [comment]
Sure that would be great. Regarding this tray, actually what OS X belongs it's possible to create much more powerful trays / notifications like [gitify](https://github.com/ekonstantinidis/gitify) or [monu](https://github.com/maxogden/monu) does for example. This basic tray functionality is only required for Windows and Linux so I'll try to come up with an idea how these tray/notifications can be modularized in the electron app and be used depending on the current OS.

**Comment by engelgabriel** [comment]
screen shot 2015-07-13 at 16 06 26

**Comment by subesokun** [comment]
@rodrigok Let me know if the latest commit helped regarding the issue with the large tray icon and that quiting the app didn't work. Do you've actually any SVG images of the rocket logo? Seems like on OS X it's more trendy to have gray scale icon and I also wanted to remove the white filling inside of the icon.

@engelgabriel Such a tray like for gitter would be awesome :) The trick seems to be to attach a browser window to the tray and then position it depending on the tray click event position ... see [here](https://github.com/ekonstantinidis/gitify/blob/5fe3a743f6ff756fdf1dcd7cc502b682baa924f0/main.js#L43)

**Comment by rodrigok** [comment]
@subesokun your latest commit fixed the large tray icon, but it is not optimized for retina screens, but it's not a problem now, I can fix this after.

captura de tela 2015-07-15 as 09 07 38

The window still minimizing when I try to quit the app or close the window.

I will fork your repository and try to fix this problem.

**Comment by rodrigok** [comment]
@subesokun can you test this branch https://github.com/RocketChat/Rocket.Chat.Electron/tree/feat-tray?

**Comment by subesokun** [comment]
@rodrigok Awesome, thanks for fixing the OS X issues :) Your changes are looking good and it works for me also on Linux :+1: Only the icon is a bit hard to see (at least on Xubuntu, but I think also on Ubuntu). Maybe an icon with filling would be good for Linux.

**Comment by rodrigok** [comment]
@subesokun can you attach one print with this problem?

**Comment by subesokun** [comment]
Here a screenshot from Xubuntu

xubuntu-tray

**Comment by rodrigok** [comment]
@subesokun we are working in this icon.

In OS X the OS changes the icon color from black to white automatically when the background is dark or the icon is selected/clicked, but in Linux we didn't found how to do this, so we are working in another solution.

**Comment by engelgabriel** [comment]
dark icon fixed.. please try again?

**Comment by subesokun** [comment]
@engelgabriel Thanks for merging it into master! Regarding the icon, visibility is now good but maybe there could be a little bit more distance between the icon and the border of the taskbar on the top and the bottom. 

xubuntu-tray-2

Also I've noticed that somehow the icon for the window in the taskbar is missing

xubuntu-taskbar

**Comment by subesokun** [comment]
Actually the windows version looks also nice on Linux (Xubuntu / Ubuntu). It just needs to be a few pixels taller. It would fit then also to the Ubuntu tray icons.

xubuntu-tray-3

(Ubuntu 15.04)
ubuntu-tray

**Comment by engelgabriel** [comment]
What about the light ubuntu team?

**Comment by subesokun** [comment]
Where can I find it?

**Comment by engelgabriel** [comment]
On option would be to turn the icon set, and option. I've seen this in other apps.

**Pull request merged**
