### PR TITLE
[FIX] Toggled tray icon notifications

### LINKED ISSUE #855: Disabling Tray Icon also disables App Icon new message notifications
## My Setup
- Operating System: macOS High Sierra
- App Version: 2.13.1

When the Tray Icon is toggled to off, the App Icon no longer indicates new messages.
As soon as it is toggled on again, new messages are also indicated in the App Icon.
This problem starts with Rocket.Chat versions newer then 2.11.0.

screen shot 2018-09-03 at 9 25 56

### PR DESCRIPTION
**Pull request by HappyTobi**
[FIX] Toggled tray icon notifications

Show correct notification count on dock while tray icon was "disabled" / not shown.

Closes #855

### CODE REVIEW

**Comment by c-hoeger** [comment]
FYI: After applying this fix to a fork from the master branch, the complete app crashes when toggling the tray icon.

**Comment by HappyTobi** [comment]
@c-hoeger you have to run the developer branch the fix was applied there

**Comment by c-hoeger** [comment]
> @c-hoeger you have to run the developer branch the fix was applied there

I cherry-picked the fix into the master branch.

But using the develop branch has the same effect. App crashes when toggling the tray icon:

```
Process:               Rocket.Chat [15209]
Path:                  /Users/USER/*/Rocket.Chat.app/Contents/MacOS/Rocket.Chat
Identifier:            chat.rocket
Version:               2.14.0-develop (35)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Rocket.Chat [15209]
User ID:               501

Date/Time:             2018-09-14 10:29:24.898 +0200
OS Version:            Mac OS X 10.13.6 (17G65)
Report Version:        12
Anonymous UUID:        783484C9-D2B6-CD18-FEEC-7C0A91518FF6


Time Awake Since Boot: 12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [0]

Application Specific Information:
Crashing on exception: -[__NSMallocBlock__ isMenuOpen]: unrecognized selector sent to instance 0x604000240ba0
[...]
```

**Comment by c-hoeger** [comment]
Problem appears to be this instruction:

`const trayDisplayed = localStorage.getItem('hideTray') === 'true';`

replacing that with

`const trayDisplayed = true`

and the crash doesn't happen anymore

**Comment by c-hoeger** [comment]
I wiped all Rocket.Chat related files from disk using AppCleaner and then I was able to toggle once. But another one leads to a crash again. I guess there are some race conditions somewhere with the localStorage in electron on mac.

**Comment by tassoevan** [comment]
Probably related to #829.

**Comment by c-hoeger** [comment]
Yes, that's the problem. And it is fixed in v2.0.9 of electron, see https://github.com/electron/electron/issues/14036.

After applying this patch, the app is no longer crashing:

```
diff --git a/package.json b/package.json
index f811494..5320b63 100644
--- a/package.json
+++ b/package.json
@@ -40,7 +40,7 @@
   "devDependencies": {
     "chai": "^4.1.2",
     "conventional-changelog-cli": "^2.0.5",
-    "electron": "^2.0.8",
+    "electron": "^2.0.9",
     "electron-builder": "^20.28.4",
     "electron-mocha": "^6.0.4",
     "eslint": "^5.5.0",
diff --git a/yarn.lock b/yarn.lock
index 84fbdf3..518233f 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -1700,9 +1700,9 @@ electron-window@^0.8.0:
   dependencies:
     is-electron-renderer "^2.0.0"

-electron@^2.0.8:
-  version "2.0.8"
-  resolved "https://registry.yarnpkg.com/electron/-/electron-2.0.8.tgz#6ec7113b356e09cc9899797e0d41ebff8163e962"
+electron@^2.0.9:
+  version "2.0.9"
+  resolved "https://registry.yarnpkg.com/electron/-/electron-2.0.9.tgz#dfc863d653fa3a2dd4fea0c63303df9c0e33c602"
   dependencies:
     "@types/node" "^8.0.24"
     electron-download "^3.0.1"
```

**Comment by isdneuroimaging** [comment]
Perhaps it's only happening for me, but with 2.13.3 I don't get the dock notification count anymore regardless if the tray (menu bar) icon is visible or not. :-(

**Pull request merged**
