### PR TITLE
Notifications on Windows XP, Vista, 7

### LINKED ISSUE #55: Desktop notification does not work on windows 7
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27758116-desktop-notification-does-not-work-on-windows-7?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LFCavalcanti**
@RocketChat/core
@rodrigok 
@geekgonecrazy 

This PR addresses the issue on #199 to restrict the notification for systems with no native support. Now only Windows XP, Vista and 7.

Closes #55.

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
@LFCavalcanti thanks for opening this!

I just tested this out locally and am getting:

```
App threw an error when running [ReferenceError: navigator is not defined]
```

Looks like navigator is not available here.

Checkout: https://github.com/electron/electron/issues/3012#issuecomment-145924640

Looks like you could: `import os from 'os';`

and do something like:

```
os.platform(); // to get platform.
os.release(); // to get os version.
```

I'm guessing you should be able to use those same version numbers you were looking for in the user agent.

Psuedo code something like:
```
if (platform === 'NT' && version < 6.2) { // https://en.wikipedia.org/wiki/Windows_NT#Releases
  // show toastr
}
```

**Comment by LFCavalcanti** [comment]
uh... oh! Electron is not a browser after all! :smile: 

I'll look into it, I'm just having a bit of trouble setting up NSIS to test the client.

**Comment by geekgonecrazy** [comment]
@LFCavalcanti you shouldn't need NSIS to test the client.  Just do: `npm install` and then `npm start` to test locally :smile:

**Comment by geekgonecrazy** [comment]
Ok 👍 I can confirm no duplicates on OSX or Windows 10.  @LFCavalcanti and this works still on windows 7?

**Comment by LFCavalcanti** [comment]
Sorry for the confusion... and a personal note: NEVER use Git GUI. haha

The next commit is correct, tested on Windows 10 and Windows 7.

**Comment by geekgonecrazy** [comment]
@rocketchat/core / @rodrigok thoughts?

**Comment by mbraun01** [comment]
@geekgonecrazy / @rodrigok 
Is there confirmation that this will be added to the next release? and is there a timeframe for that?

**Comment by geekgonecrazy** [comment]
@mbraun01 it's in master so should be in next release.  We were waiting on a few additional fixes before doing a release

**Pull request merged**
