### PR TITLE
Update upstream

### LINKED ISSUE #281: Is it possible to turn off spell check?
Most of time, we are using rocket.chat to discuss about codings, and spell check is really annoying for adding underwave to words. Uncheck the language setting in the right popup menu doesn't work, and there's no menu for disable the spell check.

### LINKED ISSUE #282: Notification problem with Release 2.1.0-Beta1
## My Setup

 - __My OS name and version__: Windows 8.1 Professional 64 Bits and Windows 10 Enterprise 64 Bits
 - __My current app version__: Release 2.1.0-Beta1

- [X ] I have tested with the latest application version (version 2.0.2 and 2.1.0-Beta1)
- [X ] I can simulate the issue easily

## Description

On a notification: The Rocket.chat's icon, in the traybar, is turning red but any notification's bubble appeared like the one I receive when I am connected trough a browser.

N.B. In the beta version, the **Test Desktop Notifications** button from the **preferences** page is not working (only tested on Windows 10)

### PR DESCRIPTION
**Pull request by rodrigok**
@RocketChat/core 

- [x] Sync with upstream
- [x] Start using electron-builder (from upstream)
- [x] Improve file organization
- [x] Make work and test spellchecker
- [x] Review background.js with background.remove.js
- [x] Keep screen size
- [x] Test window close behavior
- [x] Configure Travis to build DMG
- [x] Configure Travis to build PKG
- [x] Configure Travis to build RPM
- [x] Configure Travis to build DEB
- [x] Configure Appveyor to build EXE
- [x] Configure AppVeyor to compile to 64 and 32 bits 
- [x] Verify windows installer
- [x] Fix [both windows builds have the same name](https://github.com/electron-userland/electron-builder/issues/966#issuecomment-271266300)
- [x] Verify background of DMG
- [x] Closes #281
- [x] Closes #282
- [x] Test build for DMG
- [x] Test build for DEB
- [x] Test build for EXE
- [x] Test build for PKG
- [x] Test build for RPM

## Create new issues for:
- Configure Travis to build SNAPS
- Configure Travis to build MAS
- Configure Windows Sign

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
For the snap step you should be able to do:
```
npm run build-asar
snapcraft
```

I think there are potentially 1 or 2 permissions I hadn't finished tracking down.  But for the most part it was working.

**Comment by geekgonecrazy** [comment]
Looks like on linux the about screen is broke again, and spell check is broke again.  :+1:

**Comment by rodrigok** [comment]
@geekgonecrazy `About Screen` and `Spell check` should be working now.

**Comment by geekgonecrazy** [comment]
@rodrigok I can confirm both spell check and about window work now. :+1:

**Comment by engelgabriel** [comment]
image

**Comment by engelgabriel** [comment]
When running for the first time:

screen shot 2017-01-10 at 16 29 50

**Comment by engelgabriel** [comment]
I installed rocketchat-2.1.0-beta.2-win32-x64.exe on Windows 10-64bit and rocketchat-2.1.0-beta.2-win32-x64.exe on Windows 7-64bit. When I clicked on the notification, it did not open rocket chat.

Clicking on the notification only made the notification disappear.

**Comment by engelgabriel** [comment]
I installed rocketchat-2.1.0-beta.2-win32-x64.exe on Windows 10-64bit.  At the end of the installation, I chose “Launch RocketChat.”  It put the icon in the tray, but did not open the program screen.  I clicked on the icon in the tray and only a small window opened (see screenshot).  Clicking the maximize button did take it to full screen.  Then clicking the same button again took it to the proper size. 

image

**Comment by Sing-Li** [comment]
32 bit Windows does not work (with Beta 2).  From Joshua Williams:


I installed rocketchat-2.1.0-beta.2-win32-x64.exe on Windows 10-32bit.  At the end of the installation, I chose “Launch RocketChat”, but it did not launch.  I then tried to launch it manually from the start menu and it says, “This app can’t run on your PC.  To find a version for your PC, check with the software publisher.

I installed rocketchat-2.1.0-beta.2-win32-x64.exe on Windows 7-32bit.  At the end of the installation, I chose “Launch RocketChat”, but it did not launch.  When I launched it manually, it said, “The version of this file is not compatible with the version of Windows you’re running.  Check your computer’s system information to see whether you an x86 or x64 version of the program, and then contact the software publisher.” (screenshot1)

screen shot 2017-01-10 at 5 27 01 pm

**Comment by Sing-Li** [comment]
OSX and Windows 10 issues reported by Joshua Williams:

 In OSX RocketChat, clicking on a notification brings RocketChat to the foreground, if it is in the background.  But if RocketChat is closed (clicking the red dot), clicking on the notification will not bring RocketChat to the foreground.  I must click on the dock icon in order to open RocketChat.

In Windows 10, if RocketChat is in the background (open) and I click on a notification, it will not bring RocketChat to the foreground.

**Pull request merged**
