### PR TITLE
Fix issues with Windows 7 notifications and improve design

### LINKED ISSUE #255: Windows 10 Notification
## My Setup

 - __My OS name and version__:  Windows 10
 - __My current app version__:  1.3.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

## Description

You will get a notification, if you receive a message. When you click on this notifictation, while the app is in tray, nothing happens.

#### Current Behavior

The notification just vanishs.

#### Expected Behavior

After I click on the notification in Windows 10, the app should show up

### LINKED ISSUE #297: Notification are appearing behind other windows on windows 7
## My Setup

 - __My OS name and version__: Windows 7 Enterprise X64 SP1
 - __My current app version__: 2.2.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

Notification appearing behind other windows

#### Expected Behavior

Notifications should appear in front of all other windows

### LINKED ISSUE #305: Notifications on Windows 2008 R2 opens new window
## My Setup

 - __My OS name and version__: Windows Server 2008 R2 (not tested on Windows 7 but it should be the same)
 - __My current app version__: 2.2.1

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

I have configured the Windows taskbar to only group items if it is full.

Every time a notification is shown, a new item "toaster" is shown in the task bar. They disappear after the timeout. This behaviour is very annoying.

rocketchat

#### Expected Behavior

There shouldn't be an additional item on the taskbar.

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #297 
Closes #305
Closes #255 

- Improve notification design for Windows 7 and below
- Fix issues with notifications being displayed behind other windows
- Fix issue with multiple windows being created per notification
- Fix issue in regular notifications when clicking it doesn't open app when minimised
- Added ability to click on notifications so it takes you to the correct message

6c5bfd4071

### CODE REVIEW

**Comment by rodrigok** [comment]
@Sing-Li Can you test this on your windows 7?

**Comment by Sing-Li** [comment]
Gladly. For 64 bit win 7 anyways.  @alexbrazier. Do you have an installer build for testing this PR?  Thx

**Comment by alexbrazier** [comment]
@Sing-Li You can download the installer from here https://ci.appveyor.com/project/RocketChat/rocket-chat-electron/build/1.0.175/artifacts

I have tested it on Windows 7 x32 with no issues.

**Comment by Sing-Li** [comment]
Thanks - @alexbrazier !

**Comment by Sing-Li** [comment]
Tested on Windows 7  64 bit Home Premium.   Worked as described - including message context when notification clicked.    @rodrigok

**Comment by rodrigok** [comment]
@Sing-Li @alexbrazier awesome, thanks

**Pull request merged**
