### PR TITLE
adds notifications for windows 7

### LINKED ISSUE #55: Desktop notification does not work on windows 7
<bountysource-plugin>
---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27758116-desktop-notification-does-not-work-on-windows-7?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by cbajohr**
@RocketChat/core 
@rodrigok 

Closes #55

Adds electron-toaster and notification-shim to include notifications on windows 7

bildschirmfoto 2016-05-31 um 15 14 29

### CODE REVIEW

**Comment by cbajohr** [comment]
Just fixed a small implementation flaw. notification-shim was required on the wrong place. now all works fine.

**Comment by rodrigok** [comment]
@cbajohr we are a little busy right now, I will test your PR ASAP. Feel free to remind me if it takes many days 😄

**Comment by cbajohr** [comment]
@rodrigok I will ;-)

**Comment by geekgonecrazy** [comment]
@cbajohr do you have a screenshot of it on windows 7?  Just curious as to what it looks like :smile:

**Comment by cbajohr** [comment]
@geekgonecrazy I posted one here: https://github.com/RocketChat/Rocket.Chat.Electron/issues/55

**Comment by geekgonecrazy** [comment]
@cbajohr thanks, modified initial comment to include it.  Helps to have all info in one place when reviewing :smile:

**Comment by reda-alaoui** [comment]
Hello,

Thank you for the PR.

I just merge it in my fork.
On Windows 10, notifications are duplicated.
Not tested on Windows 7 yet.

**Comment by geekgonecrazy** [comment]
@reda-alaoui thank you for trying this and reporting it.  

@cbajohr any ideas?

**Comment by cbajohr** [comment]
@reda-alaoui can't reproduce this on my Windows 10 Build. I'm getting the standard windows notification popup only. No double notification.

**Comment by yangming860101** [comment]
@rodrigok can we merge the commits now,thanks!

**Comment by yangming860101** [comment]
@engelgabriel

**Comment by LFCavalcanti** [comment]
Come on guys... are you ignoring these PRs for the desktop clients or what?

**Comment by engelgabriel** [comment]
Sorry @LFCavalcanti , but @rodrigok has been focus on some performance improvements for the lest 3 weeks. We will test this PR tomorrow when.

**Comment by rodrigok** [comment]
Hi @cbajohr, I'm testing your PR, sorry by the delay, we was very busy these days.

Can you add some test to only show this toaster for systems that don't have native notifications?

The print screen of the problem:
captura de tela 2016-07-06 as 11 41 57

**Comment by seriema** [comment]
You can take a look at how we solved it for [our HipChat Electron wrapper](https://github.com/kvasir/HipsterChat) (especially [this line](https://github.com/kvasir/HipsterChat/blob/master/index.js#L189)). I created [electron-notification-shim](https://github.com/seriema/electron-notification-shim) with it in mind. Feel free to add any feature requests there.

We had started wrapping it all into a [electron-notifier](https://github.com/kvasir/electron-notifier) for scenarios like this PR, where you just want to add notification toasters for Electron platforms that lack it. We never got around to finishing when the Electron issue got closed as we assumed it'd be as easy on the Mac. If there's interest, we could finish it so feel free to add any issues or submit a PR there.

**Comment by LiorHaim** [comment]
Any reason for pull requests not getting any reply from owners? :(

**Comment by LFCavalcanti** [comment]
Looking at pulse and the commits, the last interaction with this repo was back in June 19, I already tried to raise attention to this several times over the chat rooms, people asked here before, at this point feels this client is abandoned.

**Comment by geekgonecrazy** [comment]
@LiorHaim / @LFCavalcanti this pull request is waiting on a response from @cbajohr the Pull Request author.  

@rodrigok response is right above on July 6th.  I know its easy to point fingers and get irritated when you want something and its not happening. 

As you can see from @rodrigok 's response above... Merging this pull request would cause poor user experience.  It would post double notifications for every message if your OS wasn't Windows 7.  That's just not something we're willing to merge in.

@cbajohr sorry for the double tag... :smile:  Do you need any help on this PR?

**Comment by LFCavalcanti** [comment]
Since @cbajohr didn't reply, I'll try to pull his fork repo and add a check to only generate this notification on Windows 7 or Vista.

**Comment by cbajohr** [comment]
Sorry, I am busy with other stuff at the moment and I don't have time to check the problem. But in someone knows a fix for it, feel free to fork my repo. 
Otherwise I will try to fix it in a few weeks. 
Sorry for the delay

**Comment by geekgonecrazy** [comment]
@cbajohr not a problem.  :smile: We fully understand that other things come up.

**Comment by LFCavalcanti** [comment]
Hey @cbajohr , no problem... I already forked your repo. Just figuring out NVM for node in Windows 10 to use NSIS to test. :+1:

**Comment by yurykats** [comment]
Any ETA for when this can be released?

**Comment by LFCavalcanti** [comment]
@yurykats , this PR is deprecated, I forked the repo and did PR #224

**Pull request closed without merging**
