### PR TITLE
Spell checker improvements

### LINKED ISSUE #195: Improve spell check settings
image

This shouldn't be considered invalid.  We need to tweak the spell checker settings
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/34580474-improve-spell-check-settings?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #263: How can I disable spellchecker?
How can I disable spellchecker?

Thanks.

### LINKED ISSUE #281: Is it possible to turn off spell check?
Most of time, we are using rocket.chat to discuss about codings, and spell check is really annoying for adding underwave to words. Uncheck the language setting in the right popup menu doesn't work, and there's no menu for disable the spell check.

### LINKED ISSUE #289: Ver 2.1.0 of Windows application is laggy and almost unusable
## My Setup

 - __My OS name and version__: Windows 10 x64 fully patched
 - __My current app version__: 2.1.0

- [x] I have tested with the latest application version
- [x] I can simulate the issue easily

#### Current Behavior

With version 2.1.0 the Electron application is super laggy and almost unusable for me. Text entered into the chat window takes seconds to appear (for example a sentance can take upto ten seconds to appear). Copy pasting a URL into the chat window, selecting text etc all suffer the same. I have reproduced this on two difference Windows 10 machines (interesteling on one Windows 10 machine I tried it seemed fine).

If I go back to version 1.3.1 of the application everything is fine again. So this issue seems to be related to version 2.1.0 of the application.

### LINKED ISSUE #306: Pasting text takes a long time to appear in chat box.
## My Setup

 - __My OS name and version : Fedora 25 
 - __My current app version__: 2.2.2

- [X] I have tested with the latest application version
- [X] I can simulate the issue easily

## Description

When text is pasted into the chat e.g. code greater than 5 lines it takes a long time for it to load and appear. This makes it look like the client has hung when in fact it hasn't. This was reported by many of my colleagues who can also replicate this issue. 
#### Current Behavior
Takes a long time to paste text to chat.

#### Expected Behavior

Should not take the length of time it does, even with node being single threaded etc.

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #195
Closes #263 
Closes #281 
Closes #289 
Closes #306 

- Tidy up spell checker implementation
- Fix issues with contractions
- Fix speed issues on windows (pasting bug) - This requires limiting spell checking to one language as switching was causing the speed issues

## TODO
- [x] Check that it is working correctly on windows

### CODE REVIEW

**Comment by alexbrazier** [comment]
This pull request will make it so you can only enable 1 language at a time, or disable all together. This change significantly improves the speed of the app, in particular the windows version when typing or pasting in text.

Does anyone have a need to be able to select multiple languages?

**Comment by rodrigok** [comment]
The limitation of one language per time only exists just to prevent users to select multiple languages or it changes the implementation? Can we keep the multi language and just alert user when select more then 1 language?

Multiple languages is very useful to me.

Thoughts here @RocketChat/core ?

**Comment by alexbrazier** [comment]
@rodrigok  The implementation has changed so that it only allows 1 at a time.

If multiple languages are need then we could disable multiple languages when using Hunspell (I think it is mostly just win 7 and below that uses this). Only issue is that we would have different implementation based on operating systems.

**Comment by alexbrazier** [comment]
I have now changed it so that if it uses Hunspell then you will only be allowed one language, otherwise it will allow multiple.

**Pull request merged**
