### PR TITLE
[IMPROVE] Remove update-remind-later-dialog

### LINKED ISSUE #1075: UX: Remove the Remind me later reminder
## My Setup
- Operating System: Windows 10
- App Version: 2.14.6
- Installation type: exe

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description
Rocket Chat really creeps me out every time I click the "Remind me later" Button. 

### Current Behavior
1. If Rocketchat has a new Update for me it displays the following window (this is **expected** Behaviour):
image

2. If I click the "Remind me later" Button another dialog is displayed (this is **Unexpected** Behaviour): 
image
3. The only option I can click is "ok"...

### Expected Behavior
Just don't display the Dialog, what purpose does it serve? I think it is just annoying. 

PS: I really love RocketChat but this freaks me out every time

### PR DESCRIPTION
**Pull request by DanielHabenicht**
@RocketChat/electron

Closes #1075 

Removes the "Remind me" pop up dialog (marked red):
image

### CODE REVIEW

**Comment by DanielHabenicht** [comment]
Should I remove the language sources aswell?

**Comment by tassoevan** [comment]
@DanielHabenicht Yes, please, wipe out the strings `Update_remind` and `Update_remind_message`.

**Comment by DanielHabenicht** [comment]
@tassoevan Removed them. Whats up with the build?

**Comment by tassoevan** [comment]
@DanielHabenicht Expired MacOS certificates 😞We're updating them ASAP.

**Comment by DanielHabenicht** [comment]
Ok, no worries. Just wanted to ensure that it had nothing to do with my changes.

**Pull request merged**
