### PR TITLE
Add rocketchat:// protocol to add/open server

### LINKED ISSUE #79: Allow launching of application via rocketchat://
It would be cool for someone to be able to put something like Join us on rocket.chat with a link and it open the app.

So links like maybe rocketchat://demo.rocket.chat
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30060548-allow-launching-of-application-via-rocketchat?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F19476668&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by alexbrazier**
@RocketChat/core 

Closes #79 

Adds/switches to server using rocketchat://server urls.

e.g. `rocketchat://demo.rocket.chat` will add/open `https://demo.rocket.chat`.
Adding `?insecure=true` will make it use `http`

~Only works on windows and macOS due to os/electron limitation.~

## Todo
- Allow opening of chat/channel
   - [ ] Linux
   - [ ] Windows
   - [ ] MacOs
- Make sure app processes url on launch
   - [x] Linux
   - [x] Windows
   - [x] MacOs

### CODE REVIEW

**Comment by geekgonecrazy** [comment]
I believe on linux, if you modify the .desktop file you can make it handle url schema by adding this:
```
MimeType=x-scheme-handler/rocketchat;
```

**Comment by gdelavald** [comment]
Testing on Ubuntu, if the app is open and I click on a link it triggers the add server correctly, however if the app is closed, it only opens without coming into focus (open as background) and does not trigger the add server popup. Also, when quitting the app sometimes a Javascript exception will get thrown and the alert will show to the user (this is a blocker).
Adding the URL to a browser tab doesn't seem to trigger the app, but I'm not sure if this is expected, since the functionality we are aiming for is for easily sharing URLs (through website or even inside RC)

**Comment by geekgonecrazy** [comment]
@gdelavald so sounds like when its getting opened with schema for some reason the afterMainWindow method doesn't get called?

**Comment by gdelavald** [comment]
Seems like this needs a refactor to use [will-finish-launching](https://electron.atom.io/docs/all/#event-will-finish-launching) event instead of the 'ready', I'll look into refactoring this.

**Comment by gdelavald** [comment]
At this point, I managed to get the app processing the rocketchat URLs on startup and when already running, this feels kinda wonky on linux, but at this point I feel like this is a victory.
The main problem was that the `add-host` event was being sent but not being received on the Servers file, because it was not ready yet or something. So I moved the dialog popup to the main process and the confirmation sends the `add-host` event.
Next step would be implementing the actual deep linking to rooms/channels.

**Comment by brodock** [comment]
what I need to do to use the `rocketchat://` protocol?

**Comment by gdelavald** [comment]
@brodock any link that contains rocketchat://<server url> should open the Rocket.Chat app on your computer if you have it installed.

**Comment by brodock** [comment]
I'm sorry, that doesn't work for me...
I tried typing this on my browser: `rocketchat://open.rocket.chat/`, tried making it a proper link etc. I'm using "Rocket.Chat+" from Mac AppStore

**Pull request merged**
