### PR TITLE
feat: Add copy image in context menu

### LINKED ISSUE #1279: Copy/Paste not working in 2.15.3
I use the Rocket chat desktop application 2.15.3.
I want to copy an message with an image to paste it in other private message.

The copy works. But it can't paste the image into my other message window.

### LINKED ISSUE #1368: Copy object (image for example) doesn't work
### Description:

When using copy from menu on pasted file (for example image), there is bug on pasting - "[object Object]" - instead pasting image. Bug is on application (currently 2.15.2) and web version.

### Steps to reproduce:

1. Go to Rocketchat
2. Copy object (from menu or right mouse click)
3. Try to paste it, get nothing :(

### Expected behavior:

Object should be copied properly.

### Actual behavior:

Pasting "[object Object]", or blank space.

rocket-copy-bug

### Server Setup Information:

- Version of Rocket.Chat Server: 1.0.0-rc.2
- Operating System: Debian 9
- Deployment Method: tar
- Number of Running Instances: 2
- DB Replicaset Oplog: yes
- NodeJS Version: v8.15.0
- MongoDB Version: 4.0.5

### LINKED ISSUE #2205: Copy image to clipboard
**Describe the bug**
If i open RC in browser i can use context menu to copy image to clipboard, but it is disabled in RC electron client

What operating system and which version?
Win10 x64, RC client 3.5.7, webclient Chrome 94 or Firefox 93

Which version of Rocket.Chat (Server)?
3.17.0

Which version of Rocket.Chat.Electron (Electron/Desktop)?
3.5.7

**To Reproduce**
1. In any chat open image preview
2. Right-click to call context-menu
3. See menu item Copy

**Expected behavior**
Have a possibility to copy image to clipboard

**Screenshots**
Screenshot_7
Screenshot_8

**Additional context**
In browsers i can use contect menu item "Copy image"

### PR DESCRIPTION
**Pull request by radiokang**
Closes #2205
Closes #1279
Closes #1368

A menu item with name 'Copy image' is added in context menu to make it possible to copy images to clipboard. So, it's not necessary to save the image first if you just want to copy it.
image

### CODE REVIEW

**Comment by jeanfbrito** [comment]
@radiokang congratulations for your contribution, I will merge it right now

**Comment by ankar84** [comment]
Tested it - works good!
Copied and then pasted in chat - all perfect!
Thanks for contribution!

**Comment by prayingmantis1979** [comment]
Thank you, works.

**Comment by giterium** [comment]
Thanks :)

**Pull request merged**
