### PR TITLE
Attachment download link fix

### PR DESCRIPTION
**Pull request by gwelchc**
Fixes attachment's links, opening a save dialog to allow the user to
save the file. Once the file has been saved, the explorer is opened
selecting the file.

### CODE REVIEW

**Comment by axeloz** [comment]
It does fix the files download from the main window. 
Still broken in the "Files list" right panel.

**Comment by gwelchc** [comment]
This should solve it. It includes some minor improvements to the code.

**Comment by axeloz** [comment]
all good. thanks

**Comment by rodrigok** [comment]
Hey guys, thanks by this PR.

Can you explain why we need this since we already added a button to start download of attachments correctly as you can see below?
captura de tela 2016-04-04 as 11 05 51

**Comment by axeloz** [comment]
Hello @rodrigok, 
The PR is about the issue https://github.com/RocketChat/Rocket.Chat.Electron/issues/158
It is **not** a feature request but **a bug fix.**

**Comment by rodrigok** [comment]
Ok, so, the issue is, we don't have the "download" button inside the attachment list, right?

It's better to add the button there instead of create a script to start download of every single external link, don't you think?

**Comment by gwelchc** [comment]
Hello @rodrigok

I find that when people sees a link they click it. If the link goes nowhere or it doesn't respond, as is the case, people trend to get confused. 

Is this a sever's feature or a client's feature? If it's a server's feature, I'm not in control of the servers and thus can't help it, the problem is still present in my case. If it's a client's feature, I wonder if the link to the left of the button does something, and what is the behavior inside the client (does it open a new browser window?, does it launch a download manager?...).

Could you please refer me to the comit of this improvement?

**Comment by axeloz** [comment]
no, the issue was: "clicking the download link did nothing at all"
yes, I think you are right: a real "download" link or button would be best but when I first posted this issue, there were absolutely no way of downloading attachments.

**Comment by axeloz** [comment]
I may be wrong but on the Web client, clicking the attachment link starts the download. 
That is why @gwelchc did reproduce the same behavior on the desktop client. 

In the futur, the attachment link should may be open the right panel with the attachment details and the download button. 
Slack offer a download link in the main window. See screenshot:
slack

**Comment by rodrigok** [comment]
@gwelchc and @axeloz this is the PR that adds the download button https://github.com/RocketChat/Rocket.Chat/pull/2594/files

It's on the server code, so you need to update your rocket.chat server. That code allows electron to open a save dialog to save the file using `target="_blank" download=""`.

But, if you click on the file's link nothing happens, maybe you can change this PR to open the external links without `download=""` in external browsers.

In web version the download starts if click on a uploaded file link because our server responds the access to the file forcing the download, so you can't see the file in your browser without download it, that was a security fix.

**Comment by gwelchc** [comment]
The download attribute solution works, but still leaves a clickable link that reacts to the user cursor and that does nothing. Thus the error occurs only when an internal link loads to a downloadable file. Maybe the PR could check when the internal attachment link is missing the download attribute, add it, and allow the normal execution of the chromium base.

I believe that since this is a client issue, and not a server issue, the fix should only occur in the client (this fix leaves web browsers with two download buttons and electron clients with only one).

**Comment by rodrigok** [comment]
@gwelchc The link should open the browser window, the button should download the file.

The link is opening the browser window that has been forcing the download when you are trying to access some uploaded file, but this will not happen if you are using S3 as upload storage.

**Comment by geekgonecrazy** [comment]
@RocketChat/core what needs done on this one?  

It does seem if we have a link and that link doesn't do anything... we should fix that, even if we have a download button.

**Comment by frdmn** [comment]
+1, my coworkers noticed the same. Downloading attachments via clicking the link doesn't work.

**Comment by jthomae1** [comment]
I just downloaded the Rocket.Chat+ app from the App Store and I had the same problem, that I couldn't either download any attachments nor see or download video clips from other channel members. If I use the web browser, everything is alright. 

I solved the problem by restarting the app. So it is possible, that the bug was not completely fixed.

**Comment by graywolf336** [comment]
The Apple App Store version is extremely out of date last time I checked.

**Pull request closed without merging**
