### PR TITLE
add screensharing support for popup jitsi mode

### LINKED ISSUE #504: ScreenSharing doesn't work in popup Jitsi mode
## My Setup
- Operating System: Mac OS 10.11.6
- App Version: 2.9.0-develop

- [x] I have tested with the latest version
- [x] I can simulate the issue easily

## Description

image

### Current Behavior

The window should show a list of possible windows for sharing.

### Expected Behavior

The list of windows for sharing is not displayed.

### PR DESCRIPTION
**Pull request by jaboko**
@RocketChat/core 

Closes #504

### CODE REVIEW

**Comment by gdelavald** [comment]
Thanks for doing this PR. I'll evaluate and get back to you if there are any changes needed.

**Comment by gdelavald** [comment]
@jaboko 
I was testing the branch with the fix but the desktop sharing still didn't show up and also when reopening the window after leaving the jitsi meeting causes the jitsi to reopen automatically and I'm not able to access Rocket.Chat again, did you run into this issue?
Could you add some screen shots or a small video of your fix working?
Thanks.

**Comment by jaboko** [comment]
@gdelavald
i made a video - http://youtu.be/ul2_i4qEqxU
also we can use `selfBrowserWindow.setAlwaysOnTop(true);`

**Comment by jszaszvari** [comment]
this is awesome. good stuff

**Comment by danchr** [comment]
I tried this change on my Mac, and I get the same results as the release and the develop branch. (I had to merge with the develop branch, though, to get it to build…)

**Comment by gdelavald** [comment]
This fix will only work when the server has the `Always open Jitsi in a new tab`, which is not the case for everyone. That's why the fix wasn't merged yet, we are looking into other ways to fix all of the cases.

**Comment by jszaszvari** [comment]
Would it not be better to merge it so that it works for at least a subset of users instead of being broken for everyone?

Just put a note that says 

"At this point Screen Sharing will only work when the server has the 'Always open Jitsi in a new tab'. We are currently working on getting it to work inline."

I'm sure you'll find a bunch of people go turn that setting on just so they would be able to use this feature.

**Comment by didierhk** [comment]
@jaboko any update on this subject ?

**Comment by anand4alls** [comment]
Hi, Can Electron Screen share feasible with iframe? I am eagerly looking for same.Tried many ways but still no success.Can anyone share their finding to help me out?

**Comment by danchr** [comment]
I posted a PR to the PR that makes it work with custom domains: https://github.com/jaboko/Rocket.Chat.Electron/pull/1

What is needed to move this forward? Is there anything I can do to help?

**Comment by danchr** [comment]
> Hi, Can Electron Screen share feasible with iframe? I am eagerly looking for same.Tried many ways but still no success.Can anyone share their finding to help me out?

I looked into it, and although I'm not terribly familiar with Electron nor with the Rocket Chat codebase, it did seem slightly harder. You have to intercept the creation of the IFRAME and inject some code — I couldn't quite figure out how to do that.

That being said, I'd argue that opening a separate window leads to a better UX at the moment, and should perhaps be the default. In particular, switching to a different chat when using the IFRAME hangs up the call — and that's almost certainly not what you'd want.

**Comment by gdelavald** [comment]
Hey folks, we decided on merging this, just looking to improve the PR a bit (since this looks copy-pasted from elsewhere), this will be in the next RC Electron release and should help a bit with the video conferences inside Rocket.Chat

**Comment by myura** [comment]
any reason this wasn't included in the 2.11 release?

**Comment by arteislt** [comment]
+1 would be really useful for our company too

**Comment by myura** [comment]
@gdelavald thank you! 😄

**Comment by arteislt** [comment]
🥇 thanks a lot! Looking forward to get an update soon :)

**Comment by nilsborg** [comment]
YES! That would be really helpful!

**Comment by ddompe** [comment]
Hi,

I was testing this change locally and found a couple bugs:
- It has a left over debug code and opens the developer tools when starting the window
- Only works for main Jitsi domain and not private installations. I guess it should be extracting the domain info from the preference panel.

**Pull request merged**
