### PR TITLE
[NEW] Allow reply notifications on Mac OS

### LINKED ISSUE #310: Use node-mac-notifier for Notifications on Mac
Would allow inline replies :+1: 

https://github.com/charliehess/node-mac-notifier

### PR DESCRIPTION
**Pull request by rodrigok**
Closes #310

@RocketChat/core

### CODE REVIEW

**Comment by rodrigok** [comment]
The new notification package for OS X does not works when compiling for windows.

**Comment by rodrigok** [comment]
Maybe we should use this library https://github.com/mikaelbr/node-notifier

**Comment by geekgonecrazy** [comment]
that'd be awesome if the reply would work on linux too.  :grin:

**Comment by gdelavald** [comment]
I'm still seeing some warnings in the console:
```
Class NotificationCenterDelegate is implemented in both Rocket.Chat.Electron/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework (0x1061c7a10) 
and Rocket.Chat.Electron/node_modules/node-mac-notifier/build/Release/Notification.node (0x10b9b39f8). One of the two will be used. Which one is undefined.
```
but the notifications are working as expected

**Pull request merged**
